name: Publish Docker Develop

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v3

      - name: "ðŸš€ docker push adapter-rest-fast-food"
        run: |
          docker push ${{ secrets.DOCKER_USER }}/adapter-rest-fast-food:develop

      - name: "ðŸš€ docker push adapter-consumer-billing-fast-food"
        run: |
          docker push ${{ secrets.DOCKER_USER }}/adapter-consumer-billing-fast-food:develop